# Generated by Django 4.1.7 on 2023-02-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gremio', '0002_campeonato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
